Sync upstream (#37)
* fix code block

* Update lib.rs

* Add table_oid and field_id to columns of prepared statements

* Simplify Debug impl of Column

* Update id types

* feat(types): add default derive to json wrapper

Adds a Default impl for `Json<T> where T: Default` allowing for other
structs to use the wrapper and implement Default.

* Update env_logger requirement from 0.10 to 0.11

Updates the requirements on [env_logger](https://github.com/rust-cli/env_logger) to permit the latest version.
- [Release notes](https://github.com/rust-cli/env_logger/releases)
- [Changelog](https://github.com/rust-cli/env_logger/blob/main/CHANGELOG.md)
- [Commits](https://github.com/rust-cli/env_logger/compare/v0.10.0...v0.11.0)

---
updated-dependencies:
- dependency-name: env_logger
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

* Update ci.yml

* Update main.rs

* add #[track_caller] to the Row::get() functions

This small quality-of-life improvement changes these errors:

thread '<unnamed>' panicked at /../.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-postgres-0.7.10/src/row.rs:151:25:
error retrieving column 0: error deserializing column 0: a Postgres value was `NULL`

to:

thread '<unnamed>' panicked at my-program.rs:100:25:
error retrieving column 0: error deserializing column 0: a Postgres value was `NULL`

* Bump CI version

* Added ReadOnly session attr

* Added ReadOnly session attr

* Update base64 requirement from 0.21 to 0.22

Updates the requirements on [base64](https://github.com/marshallpierce/rust-base64) to permit the latest version.
- [Changelog](https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md)
- [Commits](https://github.com/marshallpierce/rust-base64/compare/v0.21.0...v0.22.0)

---
updated-dependencies:
- dependency-name: base64
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

* Shrink query_opt/query_one codegen size very slightly

* use `split_once` instead of `split` to parse lsn strings

[`str::split`](https://doc.rust-lang.org/std/primitive.str.html#method.split)
allocates a vector and generates considerably more instructions when compiled
than [`str::split_once`](https://doc.rust-lang.org/std/primitive.str.html#method.split_once).

[`u64::from_str_radix(split_lo, 16)`](https://doc.rust-lang.org/std/primitive.u64.html#method.from_str_radix)
will error if the `lsn_str` contains more than one `/` so this change should
result in the same behavior as the current implementation despite not explicitly
checking this.

* Make license metadata SPDX compliant

* Update heck requirement from 0.4 to 0.5

---
updated-dependencies:
- dependency-name: heck
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

* Avoid extra clone in config if possible

Using `impl Into<String>` instead of `&str` in a fn arg allows both `&str` and `String` as parameters - thus if the caller already has a String object that it doesn't need, it can pass it in without extra cloning.

The same might be done with the password, but may require closer look.

* add simple_query to GenericClient in tokio_postgres

* feat(types): add 'js' feature for wasm

Enables the "js" feature of postgres-protocol.

* Add RowDescription to SimpleQueryMessage

* Formatting updates

* Clippy compliance

* Formatting

* Work with pools that don't support prepared statements

Introduce a new `query_with_param_types` method that allows to specify Postgres type parameters. This obviated the need to use prepared statementsjust to obtain parameter types for a query. It then combines parse, bind, and execute in a single packet.

Related: #1017, #1067

* Derive Clone for Row

* impl Debug for Statement

The lack of this common trait bound caused some unpleasantness.
For example, the following didn't compile:

let x = OnceLock::new();
let stmt = db.prepare(...)?;
x.set(stmt).expect(...); // returns Result<(), T=Statement> where T: Debug

* Fix a few nits pointed out by clippy

- ...::max_value() -> ..::MAX
- delete explicit import of signed integer types

* Handle non-UTF8 error fields

* PR Fix: Only use single clone for RowDescription

* Replace the state machine to process messages with a direct match statements

* Remove query_raw_with_param_types as per PR feedback

* PR Fix: Clone first then move

* Address review comment to rename query_with_param_types to query_typed

* Fix a clippy warning

* query_typed tweaks

* Fix cancellation of TransactionBuilder::start

* Release postgres-protocol v0.6.7

* Release postgres-types v0.2.7

* Release tokio-postgres v0.7.11

* Release postgres v0.19.8

* Add jiff support

* For `query_typed`, deal with the no-data case.

If a query returns no data, we receive `Message::NoData`, which signals
the completion of the query. However, we treated it as a no-op, leading
to processing other messages and eventual failure.

This PR fixes the issue and updates the `query_typed` tests to cover
this scenario.

* Support AIX keepalive

* Remove unecessary alias for Timestamp

* Update impl for Timestamp

The impl now directly computes `Timestamp` rather than going through
`DateTime` and `Zoned`.

* Remove impl for `Zoned`

`Timestamp` already has impl and is semantically accurate for mapping to `timestamptz`, unlike `Zoned`.
End users can do their own conversions from `Timestamp` to `Zoned` if desired.

* Rename PG_EPOCH

* Fix ToSql

This sets the smallest unit to microseconds when calculating time deltas.

Previously, the number of microseconds was expressed improperly because
the rounding was not set.

* Add jiff tests and overflow checks

This adds tests in the same fashion as the existing ones for `chrono`
and `time`.

Overflow is now handled using fallible operations.
For example, `Span:microseconds` is replaced with `Span::try_microseconds`.
Postgres infinity values are workiing as expected.

All tests are passing.

* Remove `Zoned` from docs

The implementation was previously removed as per jiff author comment.

* Fix `chrono::DateTime<Utc>` tests

`test_date_time_params` and `test_with_special_date_time_params` could fail when run with a non-UTC system time zone.

In Postgres, if no time zone is stated in the input string, then it is assumed to be in system time.
This means that in these tests, a correctly parsed `DateTime<Utc>` could be compared to an incorrectly offset time.

The offset component is now included in the test strings of these tests. This component is already present in the test strings for `time::OffsetDateTime`.

* Release postgres-derive v0.4.6

* Release postgres-types v0.2.8

* Release tokio-postgres v0.7.12

* Release postgres v0.19.9

* feat: add ssl_negotiation option

* test: updte tests for direct tls

* feat: provide built-in functions for setting ALPN

* refactor: pub use sslnegotiation

* refactor: apply review comments

* chore: update postgres for ci

* Add support for cidr 0.3 under separate feature

* add `load_balance_hosts` to `Debug` impl for `Config`

* Fix time 0.3 infinity panics

Getting `PrimitiveDateTime` panics if the value is infinity.
This commit fixes the panic.

An infinity test is added, mirroring the existing one for chrono.

* Fix clippy needless_lifetimes

* Fix clippy extra_unused_lifetimes

* Fix for Rust 2024 match ergonomics

Fixes an error related to https://doc.rust-lang.org/nightly/edition-guide/rust-2024/match-ergonomics.html

* Fix another needless_lifetimes

* Fix clippy needless_borrowed_reference

The applied suggestion for 2024 match ergonomics trips another lint.
This fixes the lint.

* Bump CI Rust version to 1.75.0

cargo tests in CI are [failing](https://github.com/sfackler/rust-postgres/actions/runs/12862700447/job/35858038081?pr=1198)
because of a dependency requirement:

```
Run cargo test --all
error: package `geo-types v0.7.15` cannot be built because it requires rustc 1.75 or newer, while the currently active rustc version is 1.74.0
Either upgrade to rustc 1.75 or newer, or use
cargo update geo-types@0.7.15 --precise ver
where `ver` is the latest version of `geo-types` supporting rustc 1.74.0
```

This bumps the Rust version so tests will run.

* Bump actions/checkout

* Empty commit (re-run CI)

* Update rand requirement from 0.8 to 0.9

Updates the requirements on [rand](https://github.com/rust-random/rand) to permit the latest version.
- [Release notes](https://github.com/rust-random/rand/releases)
- [Changelog](https://github.com/rust-random/rand/blob/master/CHANGELOG.md)
- [Commits](https://github.com/rust-random/rand/compare/0.8.5...0.9.0)

---
updated-dependencies:
- dependency-name: rand
  dependency-type: direct:production
...

Signed-off-by: dependabot[bot] <support@github.com>

* refactor: address review comments

* chore: addressed rand 0.9's deprecations

* fix build

* fix clippy

* fix wasm build

* bump getrandom

* Revert time 0.2 change

* Propagate features

* add docs

* fix ci

* Release postgres-native-tls v0.5.1

* Release postgres-openssl v0.5.1

* Release postgres-protocol v0.6.8

* Release postgres-types v0.2.9

* Release tokio-postgres v0.7.13

* Release postgres v0.19.10

* Fix typo in version in postgres’s changelog

* Only call set_tcp_user_timeout when enabled

* feat: support jiff v0.2

* WIP

* WIP

* WIP

* WIP

* WIP

* WIP

* WIP

* Clearly indicate tademdrive changelog

* Update changelog.

* Fix changelog

* Fix clippy

* Fix clippy

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: James Guthrie <JamesGuthrie@users.noreply.github.com>
Co-authored-by: Steven Fackler <sfackler@gmail.com>
Co-authored-by: Michael P. Jung <michael.jung@terreon.de>
Co-authored-by: Troy Benson <troybensonsa@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Charles Samuels <ks@ks.ax>
Co-authored-by: chandr-andr (Kiselev Aleksandr) <askiselev00@gmail.com>
Co-authored-by: novacrazy <novacrazy@gmail.com>
Co-authored-by: laxjesse <jesse@osohq.com>
Co-authored-by: Paolo Barbolini <paolo.barbolini@m4ss.net>
Co-authored-by: Yuri Astrakhan <YuriAstrakhan@gmail.com>
Co-authored-by: vsuryamurthy <v.sury@fizyr.com>
Co-authored-by: Duarte Nunes <duarte.nunes@datadoghq.com>
Co-authored-by: Dane Rigby <me@danerigby.com>
Co-authored-by: Ramnivas Laddad <ramnivas@exograph.dev>
Co-authored-by: Lev Kokotov <lev.kokotov@gmail.com>
Co-authored-by: Sidney Cammeresi <sac@cheesecake.org>
Co-authored-by: Allan Zhang <allanzhang7@gmail.com>
Co-authored-by: Qiu Chaofan <qcf@ecnelises.com>
Co-authored-by: Ning Sun <sunng@protonmail.com>
Co-authored-by: Sidney Cammeresi <sac@readyset.io>
Co-authored-by: Harris Kaufmann <harris.kaufmann@wibu.com>
Co-authored-by: Allan <6740989+allan2@users.noreply.github.com>
Co-authored-by: Kristof Mattei <864376+Kristof-Mattei@users.noreply.github.com>
Co-authored-by: Charmander <~@charmander.me>
Co-authored-by: Shawn L. <shawn@sola.sh>